version: '2'

volumes:
  queue:

services:
  postfix:
    build: .
    image: fphammerle/postfix
    ports: ['127.0.0.1:25:25']
    volumes:
    - queue:/var/spool/postfix:rw
    environment:
      POSTMAP_PATHS: |
        /etc/postfix/edit-docker-compose.yml
        /etc/postfix/replace-me
    security_opt: [no-new-privileges]
    restart: unless-stopped

# https://docs.docker.com/compose/compose-file/compose-file-v2/
